name: Deploy Website

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm install
      working-directory: HeathDataInsights.io  # Adjust the directory to match the location of your package.json file
    
    - name: Build website
      run: npm run build
      working-directory: HeathDataInsights.io  # Adjust the directory to match the location of your package.json file

    - name: Check if package.json exists
      run: test -f HeathDataInsights.io/package.json || echo "package.json not found"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: HeathDataInsights.io/build  # Adjust the directory to match your build output directory
